new: use custom jump script (q) instead of (z) found online. new: can specify interpreter to use when creating script with "cs" new: added script dockerctl to give containers created through run alias a name refactored: renamed ibin/audacious-queue to ibin/audaciousctl refactored: prefer /usr/bin/* over /bin/*, works better in docker

diff --git a/ibin/cs b/ibin/cs
--- a/ibin/cs
+++ b/ibin/cs
@@ -1,7 +1,24 @@
-#!/bin/dash
+#!/usr/bin/dash
 set -e
 
-[ -f $1 ] || echo "#!/bin/dash" > $1
-chmod +x $1
-vim $1
+die() {
+	echo >&2 "$@"
+	exit 1
+}
+
+if [ $# -eq 1 ]; then
+	interpreter="dash"
+	path="$1"
+elif [ $# -eq 2 ]; then
+	interpreter="$1"
+	path="$2"
+else
+	die "invalid number of argument: $#"
+fi
+
+if [ ! -f "$path" ]; then
+	echo "#!/usr/bin/$interpreter" > $path
+fi
+chmod +x $path
+vim $path
 
