new: vm script will apply qemu params from params.txt in vm directory

diff --git a/ibin/o b/ibin/o
--- a/ibin/o
+++ b/ibin/o
@@ -7,14 +7,15 @@ die() {
 	exit 40
 }
 
-[ -z "$1" ] && die "missing argument scp target"
-echo "$1" | grep ':' > /dev/null || die "missing ':' in scp target"
-echo "$1" | grep '@' > /dev/null || die "missing '@' in scp target"
+if [ "$1" != "" ]; then
+	echo "$1" | grep ':' > /dev/null || die "missing ':' in scp target"
+	echo "$1" | grep '@' > /dev/null || die "missing '@' in scp target"
+fi
 
 # select destination directory
 dir=$(find ~/Videos -maxdepth 1 -mindepth 1 -type d | sort | rofi -dmenu -theme gruvbox-dark)
 
-find "$dir" -type f | sort
+find "$dir" -type f -name '*.mkv' | sort
 echo
 echo "enter filename to move latest recording"
 echo
@@ -28,11 +29,11 @@ do
 			ls -l ~/Videos
 			continue
 		fi
-		index=$(ls "$dir" | sed -r '/^[0-9]+\..*\.mkv/!d;s/\..*//' | sort | tail -n 1)
+		index=$(ls "$dir" | sed -r '/^[0-9]+\..*\.mkv/!d;s/\..*//;s/^0*//' | sort -n | tail -n 1)
 		destination="$dir/$(printf '%02d' $(($index+1)))."$(echo "$line" | sed '/.mkv$/!s/$/.mkv/')
 		echo "$destination"
 		mv -v "$recording" "$destination"
-		scp "$destination" "$1"
+		[ "$1" != "" ] && scp "$destination" "$1"
 	fi
 	echo
 done
