new: dp remember last preset

diff --git a/ibin/wgetc b/ibin/wgetc
--- a/ibin/wgetc
+++ b/ibin/wgetc
@@ -23,7 +23,7 @@ url="$1"
 if [ ! -f "$2" ]
 then
 	parents "$2"
-	wget "$url" -O "$2" || [ $errors = false ] || die "wget error on '$url'"
+	wget "$url" -O "$2" && errors=false || die "wget error on '$url'"
 fi
 
 # delete cached file if it is empty
